apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-app-example
        image: mrroot501/python-app-example
        ports:
        - containerPort: 8123

---

apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  selector:
    app: python-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8123
  type: LoadBalancer
