apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-k8s-job-example
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: streaming-k8s-job-example
        env:
        - name: CREDENTIALS
          value: 123a@
