apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-k8s-job-example
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: streaming-k8s-job-example
        args:
        - python3
        - /app/main.py
        env:
        - name: CREDENTIALS
          value: "123a@"
