apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-k8s-job-example
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-k8s-job-example
            env:
            - name: CREDENTIALS
              value: 123a@
