apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
images:
- name: mrroot501/etl-k8s-job-example
  newTag: v2024.08.25
namespace: data-platform
kind: Kustomization
patchesStrategicMerge:
- cronjob_secret.yaml
