apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-k8s-job-example
spec:
  strategy:
    rollingUpdate:
      maxSurge: 4 # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 0 # specifies the maximum number of Pods that can be unavailable during the update process
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - streaming-k8s-job-example
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 900 # 15 min for preStop hook
      containers:
        - name: streaming-k8s-job-example
          image: mrroot501/streaming-k8s-job-example
          args:
          - python3
          - /app/main.py
          env:
          - name: CREDENTIALS
            value: CREDENTIALS
          resources:
            limits:
              cpu: 1
              memory: 2048Mi
            requests:
              cpu: 1
              memory: 1024Mi
