apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-k8s-job-example
spec:
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - streaming-k8s-job-example
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 900 # 15 min for preStop hook
      containers:
        env:
        - name: CREDDENTIALS
          value: CREDDENTIALS
        image: mrroot501/streaming-k8s-job-example
        name: streaming-k8s-job-example
        resources:
          limits:
            cpu: 1
            memory: 2048Mi
          requests:
            cpu: 1
            memory: 1024Mi
